# A Docker Compose must always start with the version tag.
version: '3'

services:

  app:
    image: sephiraith/planetarium:file
    container_name: planetarium
    ports:
      - 8080:8080
      - 5432:5432
    environment:
      - VARIABLE=VALUE
    volumes:
      - ./logs:/logs
  loki:
    image: grafana/loki:latest # think of this as a database for your logs
    container_name: logging-loki
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:latest
    container_name: logging-promtail
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/promtail-config.yml # configuration I made:config saved in container
      - ./logs/lifespanlogs.log:/var/log/lifespanlogs.log # log we want to save:log in promtail
    command: "--config.file=/etc/promtail/promtail-config.yml"

  grafana:
    image: grafana/grafana:latest # default username/password:admin/password
    container_name: logging-grafana
    # volumes:
    #   - grafana-data:/var/lib/grafana
    # persisting grafana settings
    ports:
      - 3000:3000
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest # think of this as your database for your metrics over time
    ports:
      - 9090:9090
    volumes:
      # - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus-config.yml:/etc/prometheus/prometheus-config.yml # passing the directory instead of just the config file for prometheus
      # - ./configs/prometheus-rules.yml:/etc/prometheus/prometheus-rules.yml
      # - prometheus-data:/prometheus
    container_name: logging-prometheus
    command: "--config.file=/etc/prometheus/prometheus-config.yml" #We need to tell prometheus what to target


  # this is the second container for our deployment
  # dependency:

  #   image: 'anotherImage'
  #   container_name: requiredContent
  #   ports:
  #     - 1234:1234